### ISSUE TITLE
Mac - cadnano 2.4.2 - QPainter

### ISSUE THREAD

**Issue by elija-feigl** [douglaslab/cadnano2#20]
On startup the following messages are printed to stdout. (before the welcome message).

``` 
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::rotate: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::translate: Painter not active
QPainter::rotate: Painter not active


Thank you for using Cadnano2.

We invite you to support the project by citing this reference:
...
```

Working on Mac Big Sur 10.4, Python 3.8, PyQt6 6.2.2

**Comment by piecycle** [comment]
This issue leads to instant crashes when trying to change the colour by clicking on the colour fields in the upper left corner of the editing screen (where it says "scaf" and "stap") after selecting the paint tool. Observed on macOS Big Sur 11.6, python 3.8.12, PyQt6-6.2.2.

**Comment by sdouglas** [comment]
@elija-feigl Yes, as you can probably guess, I've seen this. I spent a few minutes trying to track it down without success. It seems to be triggered when the [rightToolBar](https://github.com/douglaslab/cadnano2/blob/354777cf4fa17dbad41a65e98268219ab0c16b3d/cadnano2/ui/mainwindow/ui_mainwindow.py#L105) and [leftToolbar](https://github.com/douglaslab/cadnano2/blob/354777cf4fa17dbad41a65e98268219ab0c16b3d/cadnano2/ui/mainwindow/ui_mainwindow.py#L116) are added to the MainWindow, which previously caused no issues. I'd happily accept a pull request if you can fix it properly. For now, I'm going to temporarily suppress the STDOUT hope that the underlying issue is resolved in a future Qt/PyQt6 release.

@piecycle The bug you mentioned is unrelated, and I've fixed it in 354777c.

**Comment by elija-feigl** [comment]
I narrowed it down to Qt::RightToolBarArea and Qt::RightToolBarArea, but have not been able to fix it either.
The message gets printed to STDERR whenever these two fields are accessed. Therefore, this also applies if you rearrange toolbars in the GUI and move them either to the left or the right edge. It does not occur for Top and Bottom.

The message will still show up when moving the toolbars but most users will likely never do that. Thank you for resolving the issue!
